services:
  # 1. 데이터베이스 (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # 변수 처리
      MYSQL_DATABASE: team_builder
    command:
      - --default-time-zone=+09:00

  # 2. 백엔드 (Spring Boot)
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mysql://db:3306/team_builder?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD} # 변수 처리
      - GEMINI_API_KEY=${GEMINI_API_KEY} # 변수 처리

  # 3. 프론트엔드 (React / Vite)
  frontend:
    build:
      context: C:\projects\team-builder\team-builder\frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend